# Day 33 – NumPy Reshaping, Stacking & Splitting

This notebook focuses on:

- Array Reshaping
- Flattening Arrays
- Transpose Operations
- Array Stacking
- Array Splitting
- Data Transformation

 # Q1. Create a NumPy array containing
 numbers from 1 to 12.

 Reshape it into:

 - 3x4 matrix
 - 4x3 matrix
 - 2x6 matrix

 Display all results.

In [2]:
import numpy as np

arr = np.arange(1,13)

print('3X4 Matrix:\n',arr.reshape(3,4))
print('\n4X3 Matrix:\n',arr.reshape(4,3))
print('\n2X6 Matrix:\n',arr.reshape(2,6))


3X4 Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

4X3 Matrix:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

2X6 Matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


 # Q2. Create a 4x4 matrix.

 Display:

 - original shape
 - reshaped shape

 Convert it into:

 - 1D array
 - 2D array

In [3]:
arr = np.arange(1,17).reshape(4,4)
print("Original array:\n",arr)
print("\nOriginal shape:\n",arr.shape)
print("\n 1D array:\n",arr.reshape(16))
print("\n 2D array:\n",arr.reshape(4,4))

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Original shape:
 (4, 4)

 1D array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]

 2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


# Q3. Create a 3x5 matrix.

 Find:

 - shape
 - size
 - dimensions

 Then flatten the matrix.

In [6]:
arr = np.arange(1,16).reshape(3,5)
print("Shape:\n",arr.shape)
print("\nSize:\n",arr.size)
print("\nDimensions:\n",arr.ndim)

Shape:
 (3, 5)

Size:
 15

Dimensions:
 2


 # Q4. Create a 3x4 matrix.

 Perform transpose operation.

 Display:

 - original matrix
 - transposed matrix

 Compare shapes.

In [8]:
arr = np.arange(1,13).reshape(3,4)

print("Original matrix:\n",arr)
print("\nTransposed matrix:\n",arr.transpose())

Original matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed matrix:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


 # Q5. Create two arrays.

 Perform:

 - vertical stacking
 - horizontal stacking

 Display results.

In [12]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)

print('Vertical stacking:\n',np.concatenate((arr1,arr2),axis = 0))
print('\nHorizontal stacking:\n',np.concatenate((arr1,arr2),axis = 1))

Vertical stacking:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]

Horizontal stacking:
 [[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


# Q6. Create three arrays.

 Combine them using:

 - vstack()
 - hstack()
 - concatenate()

 Compare outputs.

In [13]:

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Array 3:", arr3)

vertical = np.vstack((arr1, arr2, arr3))
print("\nUsing vstack():")
print(vertical)


horizontal = np.hstack((arr1, arr2, arr3))
print("\nUsing hstack():")
print(horizontal)

concat = np.concatenate((arr1, arr2, arr3))
print("\nUsing concatenate():")
print(concat)

Array 1: [1 2 3]
Array 2: [4 5 6]
Array 3: [7 8 9]

Using vstack():
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Using hstack():
[1 2 3 4 5 6 7 8 9]

Using concatenate():
[1 2 3 4 5 6 7 8 9]


# Q7. Create a dataset containing 20 student marks.

 Split the array into:

 - 2 equal parts
 - 4 equal parts

 Display all splits.

In [17]:
arr_mark = np.random.randint(35,100,20)

print("2 equal parts:\n",np.split(arr_mark,2))
print("4 equal parts:\n",np.split(arr_mark,4))

2 equal parts:
 [array([58, 64, 49, 56, 79, 54, 81, 77, 67, 63]), array([76, 78, 53, 57, 43, 84, 64, 40, 94, 89])]
4 equal parts:
 [array([58, 64, 49, 56, 79]), array([54, 81, 77, 67, 63]), array([76, 78, 53, 57, 43]), array([84, 64, 40, 94, 89])]


 # Q8. Create a salary dataset.

 Reshape it into:

 - 5 employees × 4 months

 Calculate:

 - employee-wise average
 - monthly average

In [19]:
arr = np.random.randint(30000,50000,20).reshape(5,4)
print("Matrix:\n",arr)
print("\nEmployees-wise average:\n",np.mean(arr,axis = 0))
print("\nMonthly avetage:\n",np.mean(arr,axis = 1))

Matrix:
 [[32202 49742 47833 41303]
 [31942 39967 41174 32209]
 [42167 40319 43207 37671]
 [46589 34834 43474 46464]
 [44119 39174 37264 47665]]

Employees-wise average:
 [39403.8 40807.2 42590.4 41062.4]

Monthly avetage:
 [42770.   36323.   40841.   42840.25 42055.5 ]


 # Q9. Create a sales dataset.

 Store sales for:

 - 4 products
 - 6 months

 Generate:

 - product-wise totals
 - month-wise totals

In [20]:
sales = np.array([
    [100, 120, 110, 130, 140, 150],
    [200, 210, 220, 230, 240, 250],
    [150, 160, 170, 180, 190, 200],
    [300, 320, 310, 330, 340, 350]
])

print("Sales Dataset:")
print(sales)
product_totals = np.sum(sales, axis=1)

month_totals = np.sum(sales, axis=0)

print("\nProduct-wise Totals:")
print(product_totals)

print("\nMonth-wise Totals:")
print(month_totals)

Sales Dataset:
[[100 120 110 130 140 150]
 [200 210 220 230 240 250]
 [150 160 170 180 190 200]
 [300 320 310 330 340 350]]

Product-wise Totals:
[ 750 1350 1050 1950]

Month-wise Totals:
[750 810 810 870 910 950]


# Q10. Build a Company Performance Report.

 Create datasets for:

 - sales
 - expenses
 - profit

 Use:

 - reshape()
 - transpose()
 - stacking

 Generate:

 - department-wise analysis
 - monthly analysis
 - overall summary report

In [21]:
import numpy as np

sales = np.array([
    100000, 120000, 110000,
    150000, 160000, 170000,
    90000, 95000, 100000,
    200000, 210000, 220000
]).reshape(4, 3)

expenses = np.array([
    60000, 70000, 65000,
    90000, 95000, 100000,
    50000, 55000, 60000,
    120000, 125000, 130000
]).reshape(4, 3)

profit = sales - expenses

print("=" * 50)
print("COMPANY PERFORMANCE REPORT")
print("=" * 50)

print("\nSales Dataset")
print(sales)

print("\nExpenses Dataset")
print(expenses)

print("\nProfit Dataset")
print(profit)

print("\nSales Transpose")
print(sales.T)

combined = np.stack((sales, expenses, profit))

print("\nCombined Dataset Shape:")
print(combined.shape)

dept_sales = np.sum(sales, axis=1)
dept_expenses = np.sum(expenses, axis=1)
dept_profit = np.sum(profit, axis=1)

print("\nDEPARTMENT-WISE ANALYSIS")

for i in range(4):
    print(
        f"Department {i+1} | "
        f"Sales: {dept_sales[i]} | "
        f"Expenses: {dept_expenses[i]} | "
        f"Profit: {dept_profit[i]}"
    )

month_sales = np.sum(sales, axis=0)
month_expenses = np.sum(expenses, axis=0)
month_profit = np.sum(profit, axis=0)

print("\nMONTH-WISE ANALYSIS")

for i in range(3):
    print(
        f"Month {i+1} | "
        f"Sales: {month_sales[i]} | "
        f"Expenses: {month_expenses[i]} | "
        f"Profit: {month_profit[i]}"
    )

total_sales = np.sum(sales)
total_expenses = np.sum(expenses)
total_profit = np.sum(profit)

print("\nOVERALL SUMMARY REPORT")

print("Total Sales    :", total_sales)
print("Total Expenses :", total_expenses)
print("Total Profit   :", total_profit)

print("Average Sales  :", np.mean(sales))
print("Average Profit :", np.mean(profit))

print("=" * 50)

COMPANY PERFORMANCE REPORT

Sales Dataset
[[100000 120000 110000]
 [150000 160000 170000]
 [ 90000  95000 100000]
 [200000 210000 220000]]

Expenses Dataset
[[ 60000  70000  65000]
 [ 90000  95000 100000]
 [ 50000  55000  60000]
 [120000 125000 130000]]

Profit Dataset
[[40000 50000 45000]
 [60000 65000 70000]
 [40000 40000 40000]
 [80000 85000 90000]]

Sales Transpose
[[100000 150000  90000 200000]
 [120000 160000  95000 210000]
 [110000 170000 100000 220000]]

Combined Dataset Shape:
(3, 4, 3)

DEPARTMENT-WISE ANALYSIS
Department 1 | Sales: 330000 | Expenses: 195000 | Profit: 135000
Department 2 | Sales: 480000 | Expenses: 285000 | Profit: 195000
Department 3 | Sales: 285000 | Expenses: 165000 | Profit: 120000
Department 4 | Sales: 630000 | Expenses: 375000 | Profit: 255000

MONTH-WISE ANALYSIS
Month 1 | Sales: 540000 | Expenses: 320000 | Profit: 220000
Month 2 | Sales: 585000 | Expenses: 345000 | Profit: 240000
Month 3 | Sales: 600000 | Expenses: 355000 | Profit: 245000

OVERALL SUM