#Day 31 – NumPy Arrays Fundamentals

This notebook focuses on:
- NumPy Introduction
- Array Creation
- Array Attributes
- Data Types
- Basic Operations
- Numerical Computing Foundations

# Q1. Import NumPy and create arrays using:

- Python List
- Python Tuple

Display:
- array
- shape
- size
- ndim
- dtype

In [61]:
import numpy as np

# Array from Python List
list_array = np.array([10, 20, 30, 40, 50])

print("Array from List:")
print(list_array)
print("Shape:", list_array.shape)
print("Size:", list_array.size)
print("Dimensions:", list_array.ndim)
print("Data Type:", list_array.dtype)

print("-" * 40)

# Array from Python Tuple
tuple_array = np.array((1, 2, 3, 4, 5))

print("Array from Tuple:")
print(tuple_array)
print("Shape:", tuple_array.shape)
print("Size:", tuple_array.size)
print("Dimensions:", tuple_array.ndim)
print("Data Type:", tuple_array.dtype)

Array from List:
[10 20 30 40 50]
Shape: (5,)
Size: 5
Dimensions: 1
Data Type: int64
----------------------------------------
Array from Tuple:
[1 2 3 4 5]
Shape: (5,)
Size: 5
Dimensions: 1
Data Type: int64


# Q2. Create the following arrays:

- Array of zeros (5 elements)
- Array of ones (10 elements)
- Array of twos (8 elements)

Display all arrays.


In [62]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [63]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [64]:
np.full(8,2)

array([2, 2, 2, 2, 2, 2, 2, 2])

# Q3. Create arrays using:

- arange()
- linspace()

Generate:

- numbers from 1 to 20
- 10 evenly spaced values between 0 and 100

In [65]:
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [66]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

# Q4. Create a 4x5 matrix.

Display:

- shape
- dimensions
- total elements
- data type

In [67]:
arr = np.array([[1,2,3,4,5]
          ,[2,3,4,5,6]
          ,[3,4,5,6,7]
          ,[4,5,6,7,8]])

In [68]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [69]:
arr.shape

(4, 5)

# Q5. Perform element-wise operations on two arrays.

Operations:

- Addition
- Subtraction
- Multiplication
- Division


In [70]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [71]:
print('Addition:\n',arr + 2)

Addition:
 [[ 3  4  5  6  7]
 [ 4  5  6  7  8]
 [ 5  6  7  8  9]
 [ 6  7  8  9 10]]


In [72]:
print('Subtraction:\n',arr - 2)

Subtraction:
 [[-1  0  1  2  3]
 [ 0  1  2  3  4]
 [ 1  2  3  4  5]
 [ 2  3  4  5  6]]


In [73]:
print('Multiplication:\n',arr * 2)

Multiplication:
 [[ 2  4  6  8 10]
 [ 4  6  8 10 12]
 [ 6  8 10 12 14]
 [ 8 10 12 14 16]]


In [74]:
print('Division:\n',arr / 2)

Division:
 [[0.5 1.  1.5 2.  2.5]
 [1.  1.5 2.  2.5 3. ]
 [1.5 2.  2.5 3.  3.5]
 [2.  2.5 3.  3.5 4. ]]


# Q6. Create a salary dataset.

Calculate:

- minimum salary
- maximum salary
- average salary
- total salary expense

In [75]:
arr = np.array([50000,40000,35000,32000,52000,48000,45000])

In [76]:
print('Minimum:',np.min(arr))

Minimum: 32000


In [77]:
print('Maximumm:',np.max(arr))

Maximumm: 52000


In [78]:
print('Average:',np.sum(arr)/np.size(arr))

Average: 43142.857142857145


In [79]:
print('Total:',np.sum(arr))

Total: 302000


# Q7. Generate a random array containing
20 numbers between 1 and 100.

Find:

- highest value
- lowest value
- mean value


In [80]:
arr = np.random.randint(1,101,20)

In [81]:
print('High:',np.max(arr))
print('Lowest:',np.min(arr))
print('Mean:',np.mean(arr))

High: 99
Lowest: 5
Mean: 57.5


# Q8. Create an array of student marks.

Calculate:

- average marks
- highest marks
- lowest marks
- total marks

In [83]:
arr = np.array([89,67,90,99,87,34,45])

In [84]:
print('Average:',np.sum(arr)/np.size(arr))
print('High:',np.max(arr))
print('Lowest:',np.min(arr))
print('Total:',np.sum(arr))

Average: 73.0
High: 99
Lowest: 34
Total: 511


# Q9. Create a temperature dataset.

Store temperatures for 15 days.

Calculate:

- average temperature
- hottest day
- coldest day

In [86]:
temp_arr = np.array([12,45,34,39,23,32,1,20])

In [87]:
print('Average:',np.sum(temp_arr)/np.size(temp_arr))
print('Hottest:',np.max(temp_arr))
print('Coldest:',np.min(temp_arr))

Average: 25.75
Hottest: 45
Coldest: 1


# Q10. Build a Company Salary Analytics Report.

Create a salary dataset using NumPy.

Generate:

- employee count
- highest salary
- lowest salary
- average salary
- total salary expense

Display a complete summary report.

In [88]:
salaries = np.array([50000,45000,60000,55000,70000,48000,52000,65000,58000,62000])


In [89]:
employee_count = salaries.size
highest_salary = np.max(salaries)
lowest_salary = np.min(salaries)
average_salary = np.mean(salaries)
total_salary_expense = np.sum(salaries)