# Day 32 – NumPy Indexing, Slicing & Selection

This notebook focuses on:
- Array Indexing
- Array Slicing
- Boolean Indexing
- Conditional Filtering
- Fancy Indexing
- Data Selection Techniques

# Q1. Create a NumPy array containing numbers from 1 to 20.

 Display:

 - first element
 - last element
 - fifth element
 - tenth element

In [2]:
import numpy as np

arr = np.arange(1,21)
print('Array:',arr)
print('First Element:',arr[0])
print('Last Element:',arr[-1])
print('Fifth Element:',arr[4])
print('Tenth Element:',arr[9])

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
First Element: 1
Last Element: 20
Fifth Element: 5
Tenth Element: 10


 # Q2. Create a NumPy array containing numbers from 1 to 30.

 Extract and display:

 - first 10 elements
 - last 10 elements
 - elements from index 5 to 15
 - every second element

In [3]:
arr1 = np.arange(1,31)

print('Array:',arr1)
print('First 10 elements:',arr1[:9])
print('Last 10 elements:',arr1[-10:])
print('Element from index 5 to 15:',arr1[5:14])
print('Every Second element:',arr1[::2])

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
First 10 elements: [1 2 3 4 5 6 7 8 9]
Last 10 elements: [21 22 23 24 25 26 27 28 29 30]
Element from index 5 to 15: [ 6  7  8  9 10 11 12 13 14]
Every Second element: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]


 # Q3. Create a 5x5 matrix.

 Display:

 - first row
 - last row
 - first column
 - last column
 - center element

In [5]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [24]:
print('First Row:',arr2[0,0:])
print('Last Row:',arr2[4,0:])
print('First Column:',arr2[:,0])
print('Last Column:',arr2[:,4])
print('Center element:',arr2[2,2])

First Row: [1 2 3 4 5]
Last Row: [21 22 23 24 25]
First Column: [ 1  6 11 16 21]
Last Column: [ 5 10 15 20 25]
Center element: 13


# Q4. Create an array containing numbers from 1 to 50.

 Using boolean indexing display:

 - numbers greater than 25
 - numbers less than 10
 - even numbers only
 - odd numbers only

In [31]:
arr3 = np.arange(1,51)
print('Number greater than 25:',arr3[arr3 > 25])
print('Number less than 10:',arr3[arr3 < 10])
print('Even numbers only:',arr3[arr3%2 == 1])
print('Odd numbers only:',arr3[arr3%2 != 0])

Number greater than 25: [26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50]
Number less than 10: [1 2 3 4 5 6 7 8 9]
Even numbers only: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
Odd numbers only: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


# Q5. Create a salary dataset.

 Calculate:

 - average salary

 Display:

 - salaries greater than average salary
 - salaries less than average salary
 - highest salary
 - lowest salary

In [33]:
arr = np.array([45000,55000,50000,48000,40000,60000,65000])

avg = np.sum(arr)/np.size(arr)
print("Average Salary:",avg)
print("Salaries greater than average salary:",arr[arr > avg])
print("Salaries less than average salary:",arr[arr < avg])
print("Highest salary:",np.max(arr))
print("Lowest salary:",np.min(arr))

Average Salary: 51857.142857142855
Salaries greater than average salary: [55000 60000 65000]
Salaries less than average salary: [45000 50000 48000 40000]
Highest salary: 65000
Lowest salary: 40000


 # Q6. Create a student marks dataset.

 Display:

 - students scoring above 75
 - students scoring below 40
 - students scoring between 50 and 80

In [41]:
arr = np.random.randint(35,100,10)

print('Student Marks:',arr)
print('Students Scoring above 75:',arr[arr > 75])
print('Students Scoring below 40:',arr[arr < 40])
print("Students scoring between 50 and 80:",arr[(arr >= 50) & (arr <= 80)])

Student Marks: [81 76 89 58 39 65 92 58 96 55]
Students Scoring above 75: [81 76 89 92 96]
Students Scoring below 40: [39]
Students scoring between 50 and 80: [76 58 65 58 55]


# Q7. Create a temperature dataset for 30 days.

 Display:

 - temperatures above average
 - temperatures below average
 - hottest day temperature
 - coldest day temperature

In [42]:
arr = np.random.randint(0,50,30)

avg = np.sum(arr)/30
print('30 Days Temperature:',arr)
print('Temperature above average:',arr[arr > avg])
print('Temperature above average:',arr[arr < avg])
print('Hottest day Temperature:',np.max(arr))
print('Coldest day Temperature:',np.min(arr))

30 Days Temperature: [31 46  8 14 37 15 34 28  3 41 46 23  1 28  3 27  0 13 32 16 40 10  5 14
 22  6  6 37  7 39]
Temperature above average: [31 46 37 34 28 41 46 23 28 27 32 40 22 37 39]
Temperature above average: [ 8 14 15  3  1  3  0 13 16 10  5 14  6  6  7]
Hottest day Temperature: 46
Coldest day Temperature: 0


# Q8. Create a 6x6 matrix.

 Extract:

 - first 3 rows
 - last 3 rows
 - first 3 columns
 - last 3 columns
 - center 3x3 matrix

In [43]:
arr = np.arange(1,37).reshape(6,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [45]:
print('First 3 Rows:\n',arr[0:2,:])
print('Last 3 Rows:\n',arr[3:5,:])
print('First 3 Columns:\n',arr[:,0:2])
print('First 3 Columns:\n',arr[:,3:5])
print('Center 3X3:\n',arr[2:5,2:4])

First 3 Rows:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Last 3 Rows:
 [[19 20 21 22 23 24]
 [25 26 27 28 29 30]]
First 3 Columns:
 [[ 1  2]
 [ 7  8]
 [13 14]
 [19 20]
 [25 26]
 [31 32]]
First 3 Columns:
 [[ 4  5]
 [10 11]
 [16 17]
 [22 23]
 [28 29]
 [34 35]]
Center 3X3:
 [[15 16]
 [21 22]
 [27 28]]


# Q9. Create an array containing 25 random integers.

 Using fancy indexing display:

 - 1st element
 - 5th element
 - 10th element
 - 15th element

 Also display:

 - top 5 values
 - bottom 5 values

In [46]:
import numpy as np

arr = np.random.randint(1, 101, 25)

print("Original Array:")
print(arr)

print("1st Element :", arr[[0]])
print("5th Element :", arr[[4]])
print("10th Element:", arr[[9]])
print("15th Element:", arr[[14]])

sorted_arr = np.sort(arr)

print("\nTop 5 Values:")
print(sorted_arr[-5:])

print("\nBottom 5 Values:")
print(sorted_arr[:5])

Original Array:
[74 12 93 29 16 46 93  3 89 64 38 75 81 66 26  8 18 56 10 52 55 49  5 74
 35]
1st Element : [74]
5th Element : [16]
10th Element: [64]
15th Element: [26]

Top 5 Values:
[75 81 89 93 93]

Bottom 5 Values:
[ 3  5  8 10 12]


# Q10. Build a Company Employee Analytics Report.

 Create datasets for:

 - employee IDs
 - salaries
 - years of experience

 Generate:

 - employees with salary above average
 - employees with experience greater than 5 years
 - employees eligible for promotion

 Display a complete analytics report.

In [ ]:
import numpy as np

# Employee Dataset
employee_ids = np.array([101, 102, 103, 104, 105, 106, 107, 108])
salaries = np.array([50000, 75000, 45000, 90000, 65000, 55000, 80000, 60000])
experience = np.array([2,7,1,10,6,3,8,5])
avg_salary = np.mean(salaries)
above_avg_mask = salaries > avg_salary
experienced_mask = experience > 5
promotion_mask = (
    (experience > 5) &
    (salaries > avg_salary)
)

print("=" * 50)
print("COMPANY EMPLOYEE ANALYTICS REPORT")
print("=" * 50)
print("\nAverage Salary:", round(avg_salary, 2))
print("\nEmployees With Salary Above Average")
print(employee_ids[above_avg_mask])
print("\nEmployees With Experience > 5 Years")
print(employee_ids[experienced_mask])
print("\nEmployees Eligible For Promotion")
print(employee_ids[promotion_mask])
print("\nPromotion Details")
print("Employee IDs :", employee_ids[promotion_mask])
print("Salaries     :", salaries[promotion_mask])
print("Experience   :", experience[promotion_mask])
print("=" * 50)